/**
 * IdempotencyStore contract — exactly-once-per-key material mutation.
 *
 * Work order ref: NET-W003 §4.6 (Idempotency and concurrency safety),
 * requirement API-004 (idempotent material mutation endpoints), §6
 * (IdempotencyStore).
 *
 * The idempotency store is backed by the authoritative persistence
 * boundary (PostgreSQL authority) — it is NOT Redis coordination
 * state. Idempotency records survive restart and are never lost when
 * Redis is cleared.
 *
 * Contract:
 *  - `applyIdempotent(key, fn)` runs `fn` exactly-once-per-key.
 *  - Concurrent calls with the same key produce exactly one mutation;
 *    the others are deterministic replays returning the cached result.
 *  - Sequential replays do NOT re-invoke `fn` and return the cached result.
 *  - `fn` receives a transaction-scoped context so the mutation and the
 *    idempotency record commit atomically (or both roll back).
 *  - `withLock(key, fn)` serializes `fn` per key with NO idempotency
 *    semantics — the serialization boundary for check-then-act
 *    sequences whose idempotency key is narrower than the invariant
 *    they guard (NET-W007 policy-lineage fork prevention).
 *
 * This file defines interfaces ONLY. Concrete implementation lives in
 * src/persistence/idempotency-store.ts.
 */

import type { ExecutionContext } from "./execution-context.ts";
// NET-W004: the apply callback MAY perform its material mutation within
// the SAME authoritative transaction as the idempotency record so the
// mutation + the idempotency marker commit atomically (or both roll
// back). The AuthorityTransaction type is a core contract
// (src/core/postgres-authority.ts) so importing it here is allowed
// (core→core).
import type { AuthorityTransaction } from "./postgres-authority.ts";

/**
 * The outcome of an idempotent apply. The stored `result` is the cached
 * return value of `fn` for the first execution; replays receive the same
 * value without re-invoking `fn`.
 */
export interface IdempotentResult<T = unknown> {
  /** True iff `fn` was actually invoked for this call. */
  readonly executed: boolean;
  /** The cached result of the first execution (returned on replays too). */
  readonly result: T;
  /** Stable record id for audit/trace lineage. */
  readonly recordId: string;
}

/**
 * Context passed to the apply callback. The caller MAY use the
 * execution context for audit/trace lineage. The transaction is the
 * authoritative scope in which both the mutation and the idempotency
 * record are committed atomically.
 */
export interface IdempotentApplyContext {
  readonly execution: ExecutionContext;
  /**
   * The authoritative transaction under which the apply is running. The
   * callback MAY perform its material mutation through this transaction
   * so the mutation + the idempotency record commit atomically (or both
   * roll back) — true exactly-once-per-key material mutation (NET-W004 §4.4).
   *
   * NET-W004 addition (additive, non-breaking): existing consumers that
   * do not read this field are unaffected. The concrete implementation
   * (src/persistence/idempotency-store.ts) populates this with the same
   * {@link AuthorityTransaction} it uses for the idempotency record.
   */
  readonly transaction: AuthorityTransaction;
  /**
   * The stable record id of the idempotency record being created by
   * this apply. The callback MAY reference it in its audit lineage so
   * the audit record traces to the exact idempotency record that
   * deduplicated the mutation (NET-W004-AC-07 correct lineage).
   *
   * NET-W004 remediation addition (additive, non-breaking): the record
   * id is generated by the store BEFORE the callback runs; it is the
   * same value returned in {@link IdempotentResult.recordId}.
   */
  readonly recordId: string;
  /** Commit the apply (records the idempotency entry + the mutation). */
  readonly commit: () => Promise<void>;
  /** Roll back the apply (discards the mutation + the idempotency entry). */
  readonly rollback: () => Promise<void>;
}

export interface IdempotencyStore {
  /**
   * Apply `fn` exactly-once-per-key. The first call with a given key
   * invokes `fn`, stores the result, and returns `{ executed: true }`.
   * Subsequent calls (concurrent or sequential) with the same key do
   * NOT invoke `fn` and return `{ executed: false, result: <cached> }`.
   *
   * `fn` MUST return a JSON-serializable value (it is persisted as the
   * cached result). `fn` MAY throw; in that case no idempotency record
   * is created and a later call with the same key will invoke `fn` again.
   */
  applyIdempotent<T>(
    key: string,
    fn: (ctx: IdempotentApplyContext) => Promise<T>,
    execution: ExecutionContext,
  ): Promise<IdempotentResult<T>>;
  /**
   * Serialize `fn` per key across ALL callers of this store instance:
   * concurrent `withLock(key, …)` calls run strictly one-at-a-time in
   * call order (a FIFO queue), and the lock is held until `fn` settles
   * (including its internal transaction commits).
   *
   * This is the store's per-key mutex exposed as a first-class
   * serialization boundary — the same mechanism `applyIdempotent`
   * already relies on, which the concrete implementation documents as
   * the stand-in for PostgreSQL `SELECT … FOR UPDATE` row-level
   * locking. OpenCon is a single-process modular monolith and every
   * material mutation flows through the ONE runtime-wired store
   * instance, so a per-key mutex on that instance is a correct
   * serialization boundary (the same reasoning that underpins
   * `applyIdempotent`'s exactly-once guarantee).
   *
   * Use it when the idempotency key alone is TOO NARROW to serialize a
   * check-then-act sequence. Example (NET-W007 policy lineages): the
   * idempotency key is
   * `reputation_policy:{organizationScopeId}:{policyId}:{version}` —
   * org-scoped — so two DIFFERENT organizations concurrently creating
   * the same `policyId` would acquire different idempotency locks and
   * could both observe "no existing lineage" and both create version 1
   * (a cross-scope fork). Wrapping the apply in
   * `withLock("reputation_policy_lineage:{policyId}", …)` serializes
   * the lineage read → scope check → version check → create → commit
   * sequence under an ORGANIZATION-INDEPENDENT key, so the second
   * caller's in-transaction lineage read observes the first caller's
   * COMMITTED version and the cross-scope fork is rejected.
   *
   * `withLock` carries NO idempotency semantics — it never caches,
   * never replays; it is pure serialization. Nesting `withLock` inside
   * `withLock` for the SAME key would deadlock; distinct keys are
   * fine. `fn` MAY throw (the lock is released and the error
   * propagates).
   *
   * NET-W007 remediation addition (additive, non-breaking): consumers
   * that do not call this method are unaffected.
   */
  withLock<T>(key: string, fn: () => Promise<T>): Promise<T>;
  /** Inspect whether a key has a cached result (for tests). */
  has(key: string): Promise<boolean>;
  /** Read the cached result for a key (for tests). Returns null if absent. */
  get<T = unknown>(key: string): Promise<{ readonly result: T; readonly recordId: string } | null>;
  /** Total record count (for integrity tests). */
  count(): Promise<number>;
}

export class IdempotencyConflictError extends Error {
  public constructor(key: string) {
    super(
      `idempotency key "${key}" is already being processed by another caller; ` +
        `the caller should retry or treat the in-flight result as authoritative.`,
    );
    this.name = "IdempotencyConflictError";
  }
}
